// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtTtwa_7FpvbjdRFVxpXGoptPzG-Ava9I',
    appId: '1:519338738024:web:68eb682df534444fb516dd',
    messagingSenderId: '519338738024',
    projectId: 'catpartners',
    authDomain: 'catpartners.firebaseapp.com',
    storageBucket: 'catpartners.appspot.com',
    measurementId: 'G-L99DCXZ5X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9drKqZhpP7tLfEky5GBnQzqmtwGtfyc',
    appId: '1:519338738024:android:b2eafbb15dac4cdab516dd',
    messagingSenderId: '519338738024',
    projectId: 'catpartners',
    storageBucket: 'catpartners.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg46bvw8IYU-9QTsY9xP-qKrFCxfluj-Y',
    appId: '1:519338738024:ios:e2a3e743a10e9af1b516dd',
    messagingSenderId: '519338738024',
    projectId: 'catpartners',
    storageBucket: 'catpartners.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg46bvw8IYU-9QTsY9xP-qKrFCxfluj-Y',
    appId: '1:519338738024:ios:d519427946f3d455b516dd',
    messagingSenderId: '519338738024',
    projectId: 'catpartners',
    storageBucket: 'catpartners.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
